name: pdf_point
description: "An ultra-modern Flutter UI/UX PDF sharing app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 8.0.2
  http: 1.6.0
  file_picker: 10.3.10
  http_parser: 4.1.2
  path_provider: 2.1.5
  dio: 5.9.1
  flutter_pdfview: 1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
