name: pdf_point
description: "An ultra-modern Flutter UI/UX PDF sharing app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.2.0
  file_picker: ^8.0.0
  http_parser: ^4.0.2
  path_provider: ^2.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
